	'mobile'=>'手机号',
	'mobile_is_empty'=>'手机号为空',
	'mobile_not_exists'=>'手机号不存在',
	'please_input_mobile'=>'请输入手机号',
	'mobile_is_in_use'=>'手机号已经注册过',
	'mobile_verify_not_on'=>'未开启手机号注册',
	'mobile_create_init_pw_template'=>'。。。',